/* ---- PART 56: c3_found.js ---- */
/* PART 56 c3_found.js (found works): Dan's own paintings and music discs, built in, turn up VERY rarely in natural loot chests.
   lootFill (src/features/p16_xp_enchanting_dungeon.js: every dungeon, Dungeon Egg, buried-dungeon and spawner-vault chest) calls
   crFoundRoll(be,x,y,z) once, last, for each chest it fills. The roll is a hash of the world seed and the chest cell, NEVER Math.random,
   so the loot RNG stream (and every seeded trace) is exactly what it was: 1 chest in CRFC.RATE (40) gets ONE found work, picked
   uniformly by a second hash, in an empty slot picked by a third. The same seed and chest always roll the same way.
   Every find MINTS a fresh 1/1 work through the registry (crNew + crFinish, credited to CRFC.BY), so it hangs, plays, saves, survives
   the GC (the chest references it), never despawns and never reaches a bot (crBotNo), exactly like a work made at an easel or a record
   player. Skipped silently in Puppet Purgatory (creativity items never appear there), when the registry is full (works, serials or
   bytes: crNew's own caps, checked first so a chest never fires a "gallery full" toast) and when the chest has no empty slot.
   CR_FOUND is copied byte for byte from Dan's world (its creativity registry, works 1-7 and 10). Work 8 ('Untitled') is a blank
   64x128 canvas (exactly crArtBlank) and is left out. Nothing here runs at top level but data, and nothing runs per frame. */
const CRFC=Object.freeze({RATE:40,BY:'Dan Dingle'});
var CRFD={force:0,pick:-1,off:false,finds:0,last:null};   /* finds/last: this world's session. Tests and rigs only: force (the next N
   rolls hit), pick (>= 0: that work), off (true: no chest ever rolls, like GR.mobSpawn=false, for rigs that count works in a seeded world) */
function crFoundFreeze(o){if(o&&typeof o==='object'&&!Object.isFrozen(o)){Object.freeze(o);for(const k of Object.keys(o))crFoundFreeze(o[k]);}return o;}
/* {k:'art', t, w, h, d: the art payload} | {k:'song', t, d: the song} (the record fields crNew/crFinish take; 'by' is CRFC.BY) */
const CR_FOUND=crFoundFreeze([
  /* work 1 */ {k:'art',t:'my art',w:64,h:128,d:'BkEglmjAZwoGMGvFjFgicD9BzBIwQgi9B-Q9BLqjiIInAZ0Etio5wZuCfAS0EcDAdCcnglwN0P2Lg459CslglwI0ujMCfCsBWVBkCdCtiPDNDYLmOCpAqDwN8P0eCSYKkDNHwTwSw4KlfDMD9Hw_BGCxvPAe0ukgrYyCSMXRMB3r4WOeC4wvTwH9KDweCowQ0sB6DFwIBjBSDwMB8EYq0bYWwthyKUEvT2SC9hAfQvY6Din09uDkPQ_C0K2NgnwfrkG0N29CdjPOMaCsLZMCNDNlwfYvwrJdkqrQS2bR8CYOMPgvQSg44jT2I8Etkl-k0M8LwTYew-kL0K8M0SQcDARBlrojRoKNwEOCoJ9i9M6CKmk0NBFwImCYL2Iw5xYOaI0L2ovR5g2DlmwI0LwK2TQjA_i6fQag4pcBPajLpsCdBDx9Gg9hHojQuaI09isKDsdhPp9CYPQrYmCo3A3YvptBIFjRYLjF0thfpdBDasKCowoHYZ6XAyDsYKI2MjdhvQ3JpBIPAR2FtCsFkCei9jQehOdgsvA3ovAyDwE4LleDumBwI2Io9DoLL2XCLwEMuC9jcC4LlqDmrhMBSQ4Imi8HgqW-OaWD28BUEsGKUEuCsEguWoLmiYJJDgm2JK2JluC5aguaOgy8KCphun2sH2XxYLmhPDBmC-k2ytngiJC0FYKmDoOU_EgmnLZOhbYRweCWcI0foQgvYQq9Ew5wvAjo4GLwENvRZfAX6L2QvA7ZdE2O0O6fbwENnw9j8DuvZsD9iMAi0tlwthXD0uj9DwS-lwM2IgklKC8BjalrTwKgjUZRoL0E9mghCOfawIy4IYluDluC44vDgiYxMGlnBliNqC9PY9GMEgWOG2KgsrZI43DBwFbBYJS_mlODwPgqME9G4peCbBgavoyCQ7AZ2uOMaCtly-iPGnYwU0oLjCgS4Kqmgll_EwFYLL8MwWRgrB7Cg5xcD4LmKDjDYOQWCSw9iMDILmG2FIJRcF2JwJgqYJBL0Ngll_OK4KLwIBwWCpgvawJgnlrx8MjrwJguYN2SCeOgS8l8J2pC0cFEGYMgio5oOXwtKKfxcE6TaRmYIuXw5xOn89uCvH2fDl4OioOML69m0y9PZPOjwbYnC8sPT8OkdiNF2ai8Egy8C9v5PDMPYrBMkg8H8pfgyb0y9ihQZeDnCtKX06JIKlvArb0-CtrD4iNCuOD48Glk2Jwpp9isG0Ig9uWsGg8DoPA7ZMLZNH8SR0oPq8xsDYNHA7ZcKQXBIKkE25fyjcC_OjwEwUdCfH4Tb0Kw_FwP2fAjS2KgqWtPBvH2KwJ2-CcH2sElk0sKC6J8CQdi9Hg5fRNn0WC5fYnAR2bBfPL08GyYbZMDYJ9jMODllwtk65cGMTh4IiMUEjDg6IjYjTwJ0SCImF8fBtLYSgj5aw5gjAjawWCEZkEWDjIGcTAbgqOeD-5htrAzR8BDbIjjsH28IvTwMytjsB7al4OcfTwtCMH2TAQ0bbwP08PR8G2XAe0pwmDwCXRNmghXAnZiIJMBCCSKwSAY58OWoJIxMHikgk2eC5fxcE0IBLwaKoL2IwbJYJZXZMC9HwTLisGQoPA2C4zgl2JweCar2KkHBw4KjC4JsGgklwZfb0bD2Ig_EjDQZGDlqCeWtKC6pNPArz2ow_BJbw40GNglqiIPYiDivYT48uMTDjPQ7Z4pcDYIT2SWuicGg4poIyZBjYP7nGBl4IvZZfS8Ii5g3byXAqDjCIIqKJ2FdCfC-mLyiwToJMBLYrRoKjD9PanMEuCosHAY0oOVwEILnGg5eCthOCeUsD9uP6K0TwqCIkGwEtly-iIKKgiZAQ08DdiOlB0eaIwEtPAuDq8CcvpAZXYb0N2EOlwK2FdPB4KqrAQq4PYd0fxthDBKvAf0TZ8BDZcG2GtE8bYWwXYbg5XAdgjvBLLg8BLZoOUgZwqCJ8J6fYTg5nY7IuCSUJgrA6Cpj2GYpIJNHLgjZhsBaDiioL25YoGYJ2FooQgk2EzNgmwpbgvY_ATg4oSwWW4KmDNhKKFMCdE6M'},
  /* work 2 */ {k:'art',t:'me',w:64,h:64,d:'BjgHepcA5pfPL2DnwPMCdA42BH0DakMwDCkaiXQMKQmifQLsHoi9AtpOiOwC-iEMAt0sFhcC_AspLxJXDhPAL9EwMldrALdOiLwSFwC7Q2jwC_SonSwIjgtnrB9GwDKifBT0j8AdqS4D_JcAQZ_AH-OC6esOeXAOdui55cAy68l2DPBNuE8A64eeWODCeN2WCsA78TAONljrDBj4PAL9ky8OCuvAJNC45cG8WDjwcApjn0svhNPAI8s_K2KwtLBMvCgqOC_ZMhMHwPcApyeC9jsAtg-PQ3Dg9gtwoP7w_lwCzSwXJMH28KOCnArJurALYPZoOPgkj4LwDDTjrAj7jgr28lB-eO9Aqg9hPIKticA4jiMODjg78D7IBDw'},
  /* work 3 */ {k:'art',t:'seems to be a person',w:64,h:64,d:'BgAFGgiIAfgiMAI7ImCsBqCoAfwAgMgLiCLwGIInA-CP2CDJcD4RpfAcl4RMBOEeWsBqWoR-BHp8A10bIrAYyNwDHQ_ARgBOCoAPIJMAQNAfelgA80BAgk0BAgA8wATOC9i8A1gvxsA6yeADLYP8l8DOCWADeCfYP8A28eADeCfAEDQN4Lgeg5gkgLQONn0Ig9g36KwDnQjoLMDcuCJgA2ghjoECAC3AEDIAmAA'},
  /* work 4 */ {k:'art',t:'dandingle.store',w:128,h:64,d:'BiA4BiArgiIgbBwC6DjcBYEbB4JcEim0GYJMAuirQWgqMtmioEbhumGwF4qwC7QQgrYiL2aK4yBiEw4xBIKwHIKwCrTBwIFjLZ8LZMEBGiHwQSNBiYMaJgxsBWDFwCzQnairRNlBwSK8DI2IUEXAR2TB4qg9Am6XR8KCtLAQFjQdmwwcCoMXDgrA-DivAJuvRtlwhMMHBojg9HwaLwfawtvBRcBGKQbAK_rRMGBwTTjE6QHQiD2htmwhorjdrARg8AvgqLwI0sPRRYPD6TRMEixgdiBoPDBwovBtlw9iMAr-8F0uH04pNLpMCYK2JiIGNwQEbAzZ8IGI4PgK9LCgxRojw4OMojw42ILg9lwtkwPimjfFi-kgrARB2IwtMUHBdKLGBweNiGwQGIENvBo3ZcGinGB24rGw9E6PgrYmK9k0TLiE4TB9vAXiKCtlwtjhtnweLwOgxRsG2fBsisFB2XAXyPwUbYnCg4v7wSDwP28H0bYRwQWNg8OK8BiDwMjQcCNlwJ2PwoqwfSg_BHBtPqwWN2GBYKwLEg8FBwtkEwCPIWgn69KNBwF4rwJjQYnBNvAiNE6oqwQbYnAfg8OI4OIgdhnhMPRNvAmNwLyhMHBwKivAmC9j_GyHYPAjSwaMsLbwtvBtoWNg8Eg9mBGwNg9ON0NBi4MbB4PYXFguKTAqJw43AgWMxNky43ZcCBgcGF0voWNwO0sOCcbAUimgkwIBwM09lwIFg8H2TArSw9DcHg4pcGgk4NwaIXbw9lwtk0QHxMCtODF2sFjcH0-kBwPFjdnwaDirozA7T2TBI2IJwbQmKxoKwSDiFwfQzBQcFgkw_EiuN0K6XAjS2TBQYg_A3Jo3Z9FgqLGBwWC8H0wYxNiRQcCtOC4g2C4gQgxYLwN2JwtIETD0tmimwhMMXxNrBIxoJYgQg4gag_uKwdjo3RvkwI24K4I6QHC8SIWDivQSgqIHcOCtnwQGNB0aI8E09uDicLaE2wYzwQHZ8KKSNwwcDRYMbAe2LiMGK40HQvAjjwIidvBYKGwUGMuKDFBG2Li9qCxsFgvDg8CgfvYvBukwP09kwWNiPaF2SLjcGiPai8D4OLwIi4MbCFBGiCoMUGMomCsODwwcCtF6SM4nBAcCdKKsFjcDYPBxcCoOKsE2N0QTZheuN0XA7TBGBiODwEeG2bAiChtrBYrwXxIuNwLgkiH2oq0xMBPInbwhsCIKw4nAmK8FFwSLBGwXZwY0HbFwfziqMsC9LD08AlyWNwOjdvAqCsF28OI8LZsLz4_rRsGFwtEwKBwOguIXRtkwwcE2IwouNwSNicCwdlwLBidON0cGM4ig8Gg8BDIuDiwdlw43A4HZcLZsFgsbBAcC9EFBwIF88E08Hy8BjT2JwtnFB0TAiN2TCiLCjLD2hY3AnT2ovBtFiBHAZyKjdkwSDwK0tvDjdk4hojwTYqLG2TAdyCjZBYy2SLwtKNwtkBwXpsDoyB-4h9LANYKGwfTwUYGIXj2TBYy2QWCsHjYmDiCgcApg8OCaKtF6XTwSIeCohIPhcEywRsGBiA3gkw4ojD04PTwNyJgraidHwoPD2DqKgRtLwgYGIaDwYGIEsE0ulw9sHALQcC4pMHg9lguIWDwFsngvALoJRYPYjBY3BYyiODi9CY2IH4PYsHARg8OCsOCopwRhIPBPFBiYPDiE2SNwT5MgiweCeI4JRvFy40GL0gYouNB-sCIhARgcG8TTgvQJ4ig4pQRtuKTBIOK8GG2M4sH0wcDYPCiMGKtBIGIFtiIvC2bBopIKwTgqDjRMF0sPS6wRcHi8Eg4rGiQcGBygcEg4jg8BCKIwE9Fw4PYvB9CcHg9rBYpMKCsGBGw4MUEbZMsbA-CsFg4sGNg8CtPDienjKIsH0fAmL2XDjPCF0YGLGw4vBYqwEIOJ0wcKLjKJ-TQmLwTpMEiEwJ0TAqMsEiuNBwxsEg8AhiLDjcOC_EwaDwK0uFwM0sH0ojg9kwbaw9LBIqwtvRcE2NwJjRMPLjcCRsFFwK0sBKDwfJdsGMsE0sHjcHgrAWg8CAY0HgrRsBPTgvBYqwJ28E2bAmJwXTivA3awvMUHawTbiGwHdLDikwO2TRNmwOg8BeK9rBticBjRMF2bAY2QEYHZcCRopAcBTZOFg-ng8F0TAsHDg8BrRIPDiqNiLDjcPS2fAVB2TBMuMtGi40TAUiwcCRhMDNOMTZNPhIMYHZBY3BtjsF2sC8sYHB4mDwHQcFBwJyaDwwY3D6T7iwdiMDIJYyiEwEAcPTBwFIPZsLSg8DtlF28Fy9sUaD2EcKITZ8LR42I4ONiPawbSgoTBIMYSCbbwonAV8IwQHaiYK2OybYjRIL2bT2WJ2fJY2ITCiDcDukg8E'},
  /* work 5 */ {k:'art',t:'S',w:64,h:128,d:'BhAOCCtg_0DyCbAHiCy9A6gkwDrZpfQN4JcH0DLYnRtg70DTY3BdAt8N0DLYQ0C6CWWO0CrYV0bYMJi0DDwvZMD9Aggl2FdG2C6WeYtAk2MmPYvAnQb8L2M8I0fAe2KliNisF0GYJPCNisOWJwH5ZdioKljcAj8KwXQ7AJpYjANpYrAK4LlhDA2YtEwDiY8B6WEcCphJeC8A08bAOfH0bAJZnZsCJZ8BiC_DMDsisAl2fBJY_Ab2MllwDbYnANZjlnwDPYzAK4L8EMBCYsF0FMCpYvA2Y8ByWEsCphJZMA0mFllwCuC_CJYjANZYrAJZiwaWEcBWC9jsA78fAN5hJZYLwDDwrBtBHAV0J8L0FYJMBfRNjdBGCaEE8Hlj9DYJ4QUgk0HdmhBeCXQZgnhBnAX0bwIehWYtDYQegm8LwXQiECHQzwnB4QJcDZYjAKujMi9ArglwE9AlgiNA18YvAT0CWCaX0GNgnwXoR0H_Glm0FIJMBeCeWI0EZnQc2END5hMG0FvBDojwrD0foU8EtCfFlmwDeWKwCzRJYQwBjmLAO5hMAvgvYuWfAMvDMAu2E8Aw8PwDSWNwC_IRwB8mLAUgvAI5hMBCZwCjxZfA2Y8F2FcDPHwNmElrAI9icC_HwGvBPA-WXAfmEliMCsicB3w7ANZYuC8AtyPwCzQU2FsAV9BPAyZwIhBPAEDQWwLmLAIdBLwvYnAW0HdicBvRdhmWaCSEF4JNg6wbQT2OwGtH6PmPYuEHdBGYTYKdBHwrBoQIujfCtlwCTQyYsDYQJdCdg26IwSWJwC3QjYONHg9jMAt0P2DHQnpdgzhPoiCSEDOCKhA12D_omEDrAEDIBYA'},
  /* work 6 */ {k:'song',t:'BATEHOVEN IS HALOUS',d:{v:1,bpm:129,bars:1,key:0,tr:[{i:'piano',o:0,vol:8,m:0,n:'AQAAUEAQFAOGAIHAKKAKL'},{i:'drums',o:0,vol:8,m:0,n:'AGAAECAGEAGIAEKACLAGM'},{i:'bass',o:0,vol:8,m:0,n:'BiABmEBqIBiM'},{i:'lead',o:0,vol:8,m:0,n:'AYAAWBAUCAQDASGAWHAYIAWJAUKAMLASO'}]}},
  /* work 7 */ {k:'song',t:'MALGORATH IM COMING FOR',d:{v:1,bpm:120,bars:4,key:0,tr:[{i:'piano',o:0,vol:8,m:0,n:'BiABoABwABkEBsEByEBgIBmIBuIAMMAKNAEOAIPBiQBoQBwQAEUASUAIVAWVAkWAqWAyWDsYDyYD6Y'},{i:'bass',o:0,vol:8,m:0,n:'BiABkEBgIBkMBiQBoUBiYBscAEgAGhAKiAMjBwkBqoBksBowBm0Bq4Bi8'},{i:'pluck',o:0,vol:8,m:0,n:'ASgAUhAYiAajAQkASlAWmAYnAQoAMpAIqAGrAMsAKtAGuAEvAwwA0yBy0Bs4AQ8AQ9AQ-AQ_'}]}},
  /* work 10 */ {k:'art',t:'Mona McLarthy',w:64,h:128,d:'BrgCWqB8A1oDfA-wBC0C-gEsA5o8Ax2OwboLNjtCMAaaAvAECg8A4oiKBsAuo4X5tCNguCI28IjRMA0onwSlwCrYxKibAN6SwDfYjR0g8A-RoEwDDIvAHRPKppHK4DimXgOdGolwCqgZKiMoGwCzQ3ANNCaWgfALunpLAOKR8Az0NoCMA30CugJwMEwDMTYT6CGgcIcLQrbCwCagIwXRxAtrAIphMCTMKF0aJocCzMBSY4jwKC0XBYToR8HE0FDIhsHEocBAIcTxYimdhHAY0TBdrBtBbYjDiPCMwbSwKMicCOkMwFtlw4XAiJwE8vouZwNy8PRcEhFwTQ7rMweIEMAl6TAKh4jwP0bYSwK0sHMwXIS08BfR4RsBrYuZwGY-IFpnwrAciBfYuvwEoR8CZhIgR8TATyJwIMrvoS2bC0fARHMwM68BCubAXj8D9D9iMBkLAR0NwH4_AR0sAshcBLQzAK9CsBPZ9D4_ArSwJ0LwH_vAO4_A3RvCTMF0fAWhPAkRHBoh8F0sApo8FR4N0IwEZiHmGwNo5nBl9GwEJjHmYiHiFwNovR8H0WZwKiMeI8BOiXBTMCNE2J08CNnwLyK8tqv0eZwCCiENlwI0sBLTwNpPAqufR5iiaP7wI0sDRKUvguuIwejM86NLAzYjhkeC64rRvPaicDNLAyJ8Tp64uZ8bDo6WI-HjrAyitmrjpionpaKwF9k864SRwekTA2IfhYjRMwFPCKKpYiwbIvAe0ej40YjwGhMBXo3Ae0GK-ifAOFzIgjANtCsANHQvAa2JwAXbYrACd0GcAf9i8ACwNh3ADX2LwAR_QWwBM0EsAYdjcAKo'}
]);
/* a uniform [0,1) from the world seed, the chest cell and a salt (FNV-1a via crHash, then a murmur3 finaliser so the high bits mix) */
function crFoundU(x,y,z,salt){let h=crHash(salt+'|'+(SEED|0)+'|'+x+','+y+','+z);
  h^=h>>>16;h=Math.imul(h,0x85ebca6b);h^=h>>>13;h=Math.imul(h,0xc2b2ae35);h^=h>>>16;return (h>>>0)/4294967296;}
function crFoundOdds(x,y,z){const u=crFoundU(x,y,z,'found');
  return {u,hit:u<1/CRFC.RATE,pick:Math.floor(crFoundU(x,y,z,'found-pick')*CR_FOUND.length)};}
/* room for one more finished copy of found work f under every registry cap (the record measured exactly as crSz will measure it) */
function crFoundRoom(f){if(!f)return false;const r={k:f.k,st:'done',t:crTitle(f.t),by:crTitle(CRFC.BY),d:f.d,u:0};if(f.k==='art'){r.w=f.w;r.h=f.h;}
  return Object.keys(CRW).length<CRC.MAX_WORKS&&CRN<=CRC.MAXN&&crDLen(f.d)<=CRC.MAX_D[f.k]&&crBytes()+JSON.stringify(r).length+8<=CRC.MAX_BYTES;}
/* mint a fresh finished work from CR_FOUND[i]: {id,count:1}, or null when there is no room */
function crFoundMint(i){const f=CR_FOUND[i];if(!crFoundRoom(f))return null;
  const d=typeof f.d==='string'?f.d:JSON.parse(JSON.stringify(f.d));       /* a song gets its own unfrozen copy per work */
  const n=crNew(f.k,f.k==='art'?{w:f.w,h:f.h,d}:{d});if(!n)return null;
  const st=crFinish(n,f.t,CRFC.BY);if(!st){crDiscard(n);return null;}
  return st;}
/* the lootFill hook: maybe put ONE found work in this freshly filled chest; returns the stack it added, or null */
function crFoundRoll(be,x,y,z){if(!be||!Array.isArray(be.inv)||DIM==='puppet'||CRFD.off||!CR_FOUND.length)return null;
  let pick;
  if(CRFD.force>0){CRFD.force--;pick=crFoundOdds(x,y,z).pick;}
  else{const o=crFoundOdds(x,y,z);if(!o.hit)return null;pick=o.pick;}
  if(CRFD.pick>=0&&CRFD.pick<CR_FOUND.length)pick=CRFD.pick;
  const free=[];for(let i=0;i<be.inv.length;i++)if(!be.inv[i])free.push(i);
  if(!free.length)return null;
  const st=crFoundMint(pick);if(!st)return null;
  const slot=free[Math.floor(crFoundU(x,y,z,'found-slot')*free.length)];
  be.inv[slot]=st;CRFD.finds++;CRFD.last={x,y,z,slot,i:pick,id:st.id};return st;}
CRREG.onReset.push(()=>{CRFD.finds=0;CRFD.last=null;});
Object.assign(CREX,{CR_FOUND,CRFC,crFoundRoll,crFoundOdds,crFoundMint,crFoundRoom,getCRFD:()=>CRFD,crFoundCore:()=>({lootFill,lootChest})});

