#!/usr/bin/env python3
"""pack_mg.py (M4): embeds the Malgorath Hyperreal art into the build (bible 20; plan 5.4).

  python3 tools/art/malgorath/pack_mg.py --src <malgorath workspace> [--out FILE]
  python3 tools/art/malgorath/pack_mg.py --src <malgorath workspace> --check [--gen FILE]
  (--src defaults to $DC_MG_ART_SRC: the folder holding final/, or the final/ folder itself.) Usually run by `npm run repack`.

Reads <src>/final/<id>_{basecolor,normal,roughness,mask}.png (never modifies them) and writes (default out/art/, gitignored)
  mg_assets.gen.js        function hrMgAssets(){return {'m:<id>|b|n|r|m': 'data:image/webp;base64,...'};}
                          + module.exports.hrMgAssets (node suites); ASCII, no '<', a trailing newline
  mg_assets.manifest.json keys -> bytes, ids, fileBytes, sha1 (m4_hr.js checks coverage and the cap); next to the .gen.js
tools/assets/unpack.mjs turns it into assets/packed/mg/ (committed); the build appends it to hrassets.js byte for byte.
NEVER print the .gen.js (its lines are megabytes long). --check re-encodes in memory and compares with the build's assembled
mg_assets.gen.js (build/ or $DC_BUILD; run `npm run build` first); it writes nothing.
The header line in build() names this tool's repo path (Release 1.0, game 6.4; up to v6.3 it named the pre-repo path).
Cap: 2,400,000 bytes of file (MZ raised it from 2.2 MB). If the set does not fit, maps are re-encoded smaller in a fixed order (normals of the 1024 maps
to 512, then roughness to 256, then every 1024 map to 512) until it does: deterministic for the same inputs and Pillow."""
import argparse, base64, hashlib, io, json, os, sys
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import dcpaths  # noqa: E402  (repo-relative paths + the art workspaces from the environment)
FINAL = None                                     # set in main() from --src / $DC_MG_ART_SRC
GEN = dcpaths.R('out', 'art', 'mg_assets.gen.js')
CAP = 2_400_000  # MZ 2026-10-08: 2.2 -> 2.4 MB keeps the hide, brow and flesh albedo at 1024 (html ~43 MB of 45)
IDS = ['mg_hide', 'mg_brow', 'mg_flesh', 'mg_horn', 'mg_enamel', 'mg_eye', 'mg_crust', 'mg_bile', 'mg_char', 'face_husk']
MAPS = {'b': 'basecolor', 'n': 'normal', 'r': 'roughness', 'm': 'mask'}
Q = {'b': 82, 'n': 88, 'r': 80, 'm': 85}


def enc(path, k, size):
    im = Image.open(path); im = im.convert('L' if k in 'rm' else 'RGB')
    if size and im.size[0] > size: im = im.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO(); im.convert('RGB').save(buf, 'WEBP', quality=Q[k], method=6)
    return 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')


def build(limits):
    T = {}
    for i in IDS:
        for k, mp in MAPS.items():
            p = FINAL + '%s_%s.png' % (i, mp)
            if not os.path.exists(p): continue
            T['m:%s|%s' % (i, k)] = enc(p, k, limits.get((i, k)) or limits.get(k))
    body = 'function hrMgAssets(){return {' + ','.join('%s:%s' % (json.dumps(k), json.dumps(v)) for k, v in T.items()) + '};}\n'
    body = ('/* PART 57 HR ASSETS - GENERATED by tools/art/malgorath/pack_mg.py. Do not edit. Do not print (lines are megabytes long). */\n' + body +
            "if(typeof module!=='undefined'&&module.exports)module.exports.hrMgAssets=hrMgAssets;\n")
    return T, body


def main():
    global FINAL
    ap = argparse.ArgumentParser(description='Embed the Malgorath Hyperreal art into mg_assets.gen.js (then tools/assets/unpack.mjs)')
    ap.add_argument('--src', default=None, help='the Malgorath workspace holding final/ (default $DC_MG_ART_SRC)')
    ap.add_argument('--out', default=None, help='the .gen.js to write (default out/art/mg_assets.gen.js); the manifest goes beside it')
    ap.add_argument('--check', action='store_true', help='re-encode in memory and compare with --gen; writes nothing')
    ap.add_argument('--gen', default=None, help='--check: the assembled .gen.js (default build/mg_assets.gen.js or $DC_BUILD)')
    a = ap.parse_args()
    src = dcpaths.mg_src(a.src)
    FINAL = src + 'final/' if os.path.isdir(src + 'final') else src
    have = [i for i in IDS if os.path.exists(FINAL + i + '_basecolor.png')]
    if not have: print('pack_mg: no finals in', dcpaths.rel(FINAL), '- nothing written'); return 0
    steps = [{}, {('mg_hide', 'n'): 512, ('mg_brow', 'n'): 512, ('mg_flesh', 'n'): 512},
             {('mg_hide', 'n'): 512, ('mg_brow', 'n'): 512, ('mg_flesh', 'n'): 512, 'r': 256},
             {'b': 512, 'n': 512, 'r': 256, 'm': 512}, {'b': 512, 'n': 256, 'r': 256, 'm': 256}]
    for lim in steps:
        T, body = build(lim)
        if len(body) <= CAP: break
    assert body.isascii() and '<' not in body and body.endswith('\n') and 'function hrMgAssets(' in body
    if len(body) > CAP: print('pack_mg: %d bytes even at the smallest step (cap %d)' % (len(body), CAP)); return 1
    if a.check:
        gen = os.path.abspath(a.gen) if a.gen else dcpaths.build_dir() + 'mg_assets.gen.js'
        if not os.path.exists(gen): print('pack_mg --check: %s not found (run `npm run build` first)' % dcpaths.rel(gen)); return 1
        old = open(gen, encoding='ascii').read()
        print('pack_mg --check:', 'up to date' if old == body else 'STALE'); return 0 if old == body else 1
    out = os.path.abspath(a.out) if a.out else GEN
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'w', encoding='ascii').write(body)
    man = {'keys': {k: len(v) for k, v in T.items()}, 'ids': have, 'fileBytes': len(body), 'cap': CAP, 'limits': {str(k): v for k, v in lim.items()},
           'sha1': hashlib.sha1(body.encode('ascii')).hexdigest(), 'gen': 'pack_mg 1.0', 'file': 'mg_assets.gen.js'}
    json.dump(man, open(os.path.join(os.path.dirname(out), 'mg_assets.manifest.json'), 'w'), indent=1)
    print('pack_mg: %d keys, %d ids, %d bytes (cap %d), limits %s -> %s' % (len(T), len(have), len(body), CAP, man['limits'], dcpaths.rel(out)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
